### ISSUE TITLE
Port to python 3.

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/TortugadeMexico#1]
The activity is similar to [Turtleart](https://github.com/sugarlabs/turtleart-activity) activity which has been ported to python3, make necessary changes to this activity.

**Comment by srevinsaju** [comment]
@chimosky Turtleart is not ported to GLibTelepathy, is there any activity where I can refer to GLIbTelepathy ported ones?

**Comment by chimosky** [comment]
Yeah I just noticed, see the port to [TelepathyGLib project](https://github.com/orgs/sugarlabs/projects/4#column-272150) for already ported activities.

**Comment by chimosky** [comment]
Also for porting to python3 we port to TelepathyGLib via dbus, we use TelepathyGLib for constants and dbus for operations. See the [python3 porting guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md), also here's a [commit](https://github.com/sugarlabs/speak/commit/f199219483cf5f320462c93b9aced0ec0ed005da) that should give you an idea.

**Comment by srevinsaju** [comment]
Thanks @chimosky . If I first port TurtleArt, instead of TortugadeMexico, will it be accepted as another Port to Telepathy Task on GCI? Thanks
